n=int(input())
i=1
l=1
while(i<=n):
    s=1
    while(s<=n-i):
        print(' ',end='')
        s+=1
    j=1
    while(j<=i):
        print(l,end=" ")
        l+=1
        j+=1
    k=2*i-2
    while(k>=i):
        print(k,end=" ")
        k-=1
    print()
    i+=1
